//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PucpConnectPresentacion.InteresWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", ConfigurationName="InteresWS.InteresWS")]
    public interface InteresWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/InteresWS/listarInteresRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/InteresWS/listarInteresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.InteresWS.listarInteresResponse listarInteres(PucpConnectPresentacion.InteresWS.listarInteresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/InteresWS/listarInteresRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/InteresWS/listarInteresResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.InteresWS.listarInteresResponse> listarInteresAsync(PucpConnectPresentacion.InteresWS.listarInteresRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class interes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInteres", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarInteresRequest {
        
        public listarInteresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInteresResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarInteresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.InteresWS.interes[] @return;
        
        public listarInteresResponse() {
        }
        
        public listarInteresResponse(PucpConnectPresentacion.InteresWS.interes[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InteresWSChannel : PucpConnectPresentacion.InteresWS.InteresWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InteresWSClient : System.ServiceModel.ClientBase<PucpConnectPresentacion.InteresWS.InteresWS>, PucpConnectPresentacion.InteresWS.InteresWS {
        
        public InteresWSClient() {
        }
        
        public InteresWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InteresWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InteresWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InteresWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.InteresWS.listarInteresResponse PucpConnectPresentacion.InteresWS.InteresWS.listarInteres(PucpConnectPresentacion.InteresWS.listarInteresRequest request) {
            return base.Channel.listarInteres(request);
        }
        
        public PucpConnectPresentacion.InteresWS.interes[] listarInteres() {
            PucpConnectPresentacion.InteresWS.listarInteresRequest inValue = new PucpConnectPresentacion.InteresWS.listarInteresRequest();
            PucpConnectPresentacion.InteresWS.listarInteresResponse retVal = ((PucpConnectPresentacion.InteresWS.InteresWS)(this)).listarInteres(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.InteresWS.listarInteresResponse> PucpConnectPresentacion.InteresWS.InteresWS.listarInteresAsync(PucpConnectPresentacion.InteresWS.listarInteresRequest request) {
            return base.Channel.listarInteresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.InteresWS.listarInteresResponse> listarInteresAsync() {
            PucpConnectPresentacion.InteresWS.listarInteresRequest inValue = new PucpConnectPresentacion.InteresWS.listarInteresRequest();
            return ((PucpConnectPresentacion.InteresWS.InteresWS)(this)).listarInteresAsync(inValue);
        }
    }
}
