//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PucpConnectPresentacion.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", ConfigurationName="UsuarioWS.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/UsuarioWS/registrarAlumnoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/UsuarioWS/registrarAlumnoResponse")]
        PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse registrarAlumno(PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/UsuarioWS/registrarAlumnoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/UsuarioWS/registrarAlumnoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse> registrarAlumnoAsync(PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAlumno", Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        public PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequestBody Body;
        
        public registrarAlumnoRequest() {
        }
        
        public registrarAlumnoRequest(PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarAlumnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string carrera;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fotoPerfil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ubicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string biografia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool visible;
        
        public registrarAlumnoRequestBody() {
        }
        
        public registrarAlumnoRequestBody(string nombre, string password, bool estado, string email, int edad, string carrera, string fotoPerfil, string ubicacion, string biografia, bool visible) {
            this.nombre = nombre;
            this.password = password;
            this.estado = estado;
            this.email = email;
            this.edad = edad;
            this.carrera = carrera;
            this.fotoPerfil = fotoPerfil;
            this.ubicacion = ubicacion;
            this.biografia = biografia;
            this.visible = visible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAlumnoResponse", Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        public PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponseBody Body;
        
        public registrarAlumnoResponse() {
        }
        
        public registrarAlumnoResponse(PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarAlumnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public registrarAlumnoResponseBody() {
        }
        
        public registrarAlumnoResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : PucpConnectPresentacion.UsuarioWS.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<PucpConnectPresentacion.UsuarioWS.UsuarioWS>, PucpConnectPresentacion.UsuarioWS.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse PucpConnectPresentacion.UsuarioWS.UsuarioWS.registrarAlumno(PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest request) {
            return base.Channel.registrarAlumno(request);
        }
        
        public bool registrarAlumno(string nombre, string password, bool estado, string email, int edad, string carrera, string fotoPerfil, string ubicacion, string biografia, bool visible) {
            PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest inValue = new PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest();
            inValue.Body = new PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            inValue.Body.estado = estado;
            inValue.Body.email = email;
            inValue.Body.edad = edad;
            inValue.Body.carrera = carrera;
            inValue.Body.fotoPerfil = fotoPerfil;
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.biografia = biografia;
            inValue.Body.visible = visible;
            PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse retVal = ((PucpConnectPresentacion.UsuarioWS.UsuarioWS)(this)).registrarAlumno(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse> PucpConnectPresentacion.UsuarioWS.UsuarioWS.registrarAlumnoAsync(PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest request) {
            return base.Channel.registrarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.UsuarioWS.registrarAlumnoResponse> registrarAlumnoAsync(string nombre, string password, bool estado, string email, int edad, string carrera, string fotoPerfil, string ubicacion, string biografia, bool visible) {
            PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest inValue = new PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequest();
            inValue.Body = new PucpConnectPresentacion.UsuarioWS.registrarAlumnoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            inValue.Body.estado = estado;
            inValue.Body.email = email;
            inValue.Body.edad = edad;
            inValue.Body.carrera = carrera;
            inValue.Body.fotoPerfil = fotoPerfil;
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.biografia = biografia;
            inValue.Body.visible = visible;
            return ((PucpConnectPresentacion.UsuarioWS.UsuarioWS)(this)).registrarAlumnoAsync(inValue);
        }
    }
}
