//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PucpConnectPresentacion.MensajeWSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", ConfigurationName="MensajeWSReference.MensajeWS")]
    public interface MensajeWS {
        
        // CODEGEN: El parámetro 'mensajeId' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/eliminarMensajeRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/eliminarMensajeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse eliminarMensaje(PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/eliminarMensajeRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/eliminarMensajeResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse> eliminarMensajeAsync(PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/enviarMensajeRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/enviarMensajeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse enviarMensaje(PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/enviarMensajeRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/enviarMensajeResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse> enviarMensajeAsync(PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/obtenerMensajesEntreUsuariosRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/obtenerMensajesEntreUsuariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse obtenerMensajesEntreUsuarios(PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/obtenerMensajesEntreUsuariosRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/MensajeWS/obtenerMensajesEntreUsuariosResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse> obtenerMensajesEntreUsuariosAsync(PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMensaje", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class eliminarMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mensajeId;
        
        public eliminarMensajeRequest() {
        }
        
        public eliminarMensajeRequest(int mensajeId) {
            this.mensajeId = mensajeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMensajeResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class eliminarMensajeResponse {
        
        public eliminarMensajeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMensaje", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class enviarMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int emisorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int receptorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contenido;
        
        public enviarMensajeRequest() {
        }
        
        public enviarMensajeRequest(int emisorId, int receptorId, string contenido) {
            this.emisorId = emisorId;
            this.receptorId = receptorId;
            this.contenido = contenido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMensajeResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class enviarMensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public enviarMensajeResponse() {
        }
        
        public enviarMensajeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class mensajeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contenidoField;
        
        private int emisorIdField;
        
        private int receptorIdField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int emisorId {
            get {
                return this.emisorIdField;
            }
            set {
                this.emisorIdField = value;
                this.RaisePropertyChanged("emisorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int receptorId {
            get {
                return this.receptorIdField;
            }
            set {
                this.receptorIdField = value;
                this.RaisePropertyChanged("receptorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMensajesEntreUsuarios", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class obtenerMensajesEntreUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int emisorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int receptorId;
        
        public obtenerMensajesEntreUsuariosRequest() {
        }
        
        public obtenerMensajesEntreUsuariosRequest(int emisorId, int receptorId) {
            this.emisorId = emisorId;
            this.receptorId = receptorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMensajesEntreUsuariosResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class obtenerMensajesEntreUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.MensajeWSReference.mensajeDTO[] @return;
        
        public obtenerMensajesEntreUsuariosResponse() {
        }
        
        public obtenerMensajesEntreUsuariosResponse(PucpConnectPresentacion.MensajeWSReference.mensajeDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MensajeWSChannel : PucpConnectPresentacion.MensajeWSReference.MensajeWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensajeWSClient : System.ServiceModel.ClientBase<PucpConnectPresentacion.MensajeWSReference.MensajeWS>, PucpConnectPresentacion.MensajeWSReference.MensajeWS {
        
        public MensajeWSClient() {
        }
        
        public MensajeWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MensajeWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajeWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajeWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse PucpConnectPresentacion.MensajeWSReference.MensajeWS.eliminarMensaje(PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest request) {
            return base.Channel.eliminarMensaje(request);
        }
        
        public void eliminarMensaje(int mensajeId) {
            PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest inValue = new PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest();
            inValue.mensajeId = mensajeId;
            PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse retVal = ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).eliminarMensaje(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse> PucpConnectPresentacion.MensajeWSReference.MensajeWS.eliminarMensajeAsync(PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest request) {
            return base.Channel.eliminarMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.eliminarMensajeResponse> eliminarMensajeAsync(int mensajeId) {
            PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest inValue = new PucpConnectPresentacion.MensajeWSReference.eliminarMensajeRequest();
            inValue.mensajeId = mensajeId;
            return ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).eliminarMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse PucpConnectPresentacion.MensajeWSReference.MensajeWS.enviarMensaje(PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest request) {
            return base.Channel.enviarMensaje(request);
        }
        
        public int enviarMensaje(int emisorId, int receptorId, string contenido) {
            PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest inValue = new PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest();
            inValue.emisorId = emisorId;
            inValue.receptorId = receptorId;
            inValue.contenido = contenido;
            PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse retVal = ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).enviarMensaje(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse> PucpConnectPresentacion.MensajeWSReference.MensajeWS.enviarMensajeAsync(PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest request) {
            return base.Channel.enviarMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.enviarMensajeResponse> enviarMensajeAsync(int emisorId, int receptorId, string contenido) {
            PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest inValue = new PucpConnectPresentacion.MensajeWSReference.enviarMensajeRequest();
            inValue.emisorId = emisorId;
            inValue.receptorId = receptorId;
            inValue.contenido = contenido;
            return ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).enviarMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse PucpConnectPresentacion.MensajeWSReference.MensajeWS.obtenerMensajesEntreUsuarios(PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest request) {
            return base.Channel.obtenerMensajesEntreUsuarios(request);
        }
        
        public PucpConnectPresentacion.MensajeWSReference.mensajeDTO[] obtenerMensajesEntreUsuarios(int emisorId, int receptorId) {
            PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest inValue = new PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest();
            inValue.emisorId = emisorId;
            inValue.receptorId = receptorId;
            PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse retVal = ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).obtenerMensajesEntreUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse> PucpConnectPresentacion.MensajeWSReference.MensajeWS.obtenerMensajesEntreUsuariosAsync(PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest request) {
            return base.Channel.obtenerMensajesEntreUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosResponse> obtenerMensajesEntreUsuariosAsync(int emisorId, int receptorId) {
            PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest inValue = new PucpConnectPresentacion.MensajeWSReference.obtenerMensajesEntreUsuariosRequest();
            inValue.emisorId = emisorId;
            inValue.receptorId = receptorId;
            return ((PucpConnectPresentacion.MensajeWSReference.MensajeWS)(this)).obtenerMensajesEntreUsuariosAsync(inValue);
        }
    }
}
