//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PucpConnectPresentacion.EventoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", ConfigurationName="EventoWS.EventoWS")]
    public interface EventoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse cancelarParticipacion(PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse> cancelarParticipacionAsync(PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/buscarEventoPorIdRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/buscarEventoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse buscarEventoPorId(PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/buscarEventoPorIdRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/buscarEventoPorIdResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse> buscarEventoPorIdAsync(PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/crearEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/crearEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.crearEventoResponse crearEvento(PucpConnectPresentacion.EventoWS.crearEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/crearEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/crearEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.crearEventoResponse> crearEventoAsync(PucpConnectPresentacion.EventoWS.crearEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.listarEventosResponse listarEventos(PucpConnectPresentacion.EventoWS.listarEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosResponse> listarEventosAsync(PucpConnectPresentacion.EventoWS.listarEventosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/unirseAEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/unirseAEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.unirseAEventoResponse unirseAEvento(PucpConnectPresentacion.EventoWS.unirseAEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/unirseAEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/unirseAEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.unirseAEventoResponse> unirseAEventoAsync(PucpConnectPresentacion.EventoWS.unirseAEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosPorInteresRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosPorInteresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse listarEventosPorInteres(PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosPorInteresRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarEventosPorInteresResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse> listarEventosPorInteresAsync(PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarInteresesPorEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarInteresesPorEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse listarInteresesPorEvento(PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarInteresesPorEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarInteresesPorEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse> listarInteresesPorEventoAsync(PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse cancelarParticipacionEvento(PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/cancelarParticipacionEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse> cancelarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/verificarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/verificarParticipacionEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse verificarParticipacionEvento(PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/verificarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/verificarParticipacionEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse> verificarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/registrarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/registrarParticipacionEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse registrarParticipacionEvento(PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/registrarParticipacionEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/registrarParticipacionEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse> registrarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarParticipantesPorEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarParticipantesPorEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse listarParticipantesPorEvento(PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarParticipantesPorEventoRequest", ReplyAction="http://ws.pucpconnect.pe.edu.pucp/EventoWS/listarParticipantesPorEventoResponse")]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse> listarParticipantesPorEventoAsync(PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarParticipacion", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class cancelarParticipacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public cancelarParticipacionRequest() {
        }
        
        public cancelarParticipacionRequest(int idEvento, int idAlumno) {
            this.idEvento = idEvento;
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarParticipacionResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class cancelarParticipacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelarParticipacionResponse() {
        }
        
        public cancelarParticipacionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno creadorField;
        
        private string descripcionField;
        
        private bool estadoField;
        
        private localDateTime fechaField;
        
        private localDateTime fechaFinField;
        
        private string fechaFinStringField;
        
        private string fechaStringField;
        
        private int idEventoField;
        
        private string imagenField;
        
        private interes[] interesesField;
        
        private string nombreField;
        
        private alumno[] participantesField;
        
        private reaccion[] reaccionesField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno creador {
            get {
                return this.creadorField;
            }
            set {
                this.creadorField = value;
                this.RaisePropertyChanged("creador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaFinString {
            get {
                return this.fechaFinStringField;
            }
            set {
                this.fechaFinStringField = value;
                this.RaisePropertyChanged("fechaFinString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaString {
            get {
                return this.fechaStringField;
            }
            set {
                this.fechaStringField = value;
                this.RaisePropertyChanged("fechaString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
                this.RaisePropertyChanged("idEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("imagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intereses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public interes[] intereses {
            get {
                return this.interesesField;
            }
            set {
                this.interesesField = value;
                this.RaisePropertyChanged("intereses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public alumno[] participantes {
            get {
                return this.participantesField;
            }
            set {
                this.participantesField = value;
                this.RaisePropertyChanged("participantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reacciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public reaccion[] reacciones {
            get {
                return this.reaccionesField;
            }
            set {
                this.reaccionesField = value;
                this.RaisePropertyChanged("reacciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class alumno : usuario {
        
        private string biografiaField;
        
        private string carreraField;
        
        private int edadField;
        
        private string fotoPerfilField;
        
        private int idAlumnoField;
        
        private System.Nullable<int>[] idsAlumnosBloqueadosField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string biografia {
            get {
                return this.biografiaField;
            }
            set {
                this.biografiaField = value;
                this.RaisePropertyChanged("biografia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string carrera {
            get {
                return this.carreraField;
            }
            set {
                this.carreraField = value;
                this.RaisePropertyChanged("carrera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                this.fotoPerfilField = value;
                this.RaisePropertyChanged("fotoPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idsAlumnosBloqueados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int>[] idsAlumnosBloqueados {
            get {
                return this.idsAlumnosBloqueadosField;
            }
            set {
                this.idsAlumnosBloqueadosField = value;
                this.RaisePropertyChanged("idsAlumnosBloqueados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private bool estadoField;
        
        private localDateTime fechaRegistroField;
        
        private int idField;
        
        private string nombreField;
        
        private string passwordField;
        
        private bool visibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
                this.RaisePropertyChanged("visible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int autorField;
        
        private string contenidoField;
        
        private bool estadoField;
        
        private localDateTime fechaField;
        
        private int idPostField;
        
        private string imagenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPost {
            get {
                return this.idPostField;
            }
            set {
                this.idPostField = value;
                this.RaisePropertyChanged("idPost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("imagen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class comentario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno autorField;
        
        private string contenidoField;
        
        private bool estadoField;
        
        private localDateTime fechaComentarioField;
        
        private int idComentarioField;
        
        private post postField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaComentario {
            get {
                return this.fechaComentarioField;
            }
            set {
                this.fechaComentarioField = value;
                this.RaisePropertyChanged("fechaComentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idComentario {
            get {
                return this.idComentarioField;
            }
            set {
                this.idComentarioField = value;
                this.RaisePropertyChanged("idComentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public post post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
                this.RaisePropertyChanged("post");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class reaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comentario comentarioField;
        
        private evento eventoField;
        
        private localDateTime fechaField;
        
        private int idField;
        
        private post postField;
        
        private reaccionTipo tipoField;
        
        private bool tipoFieldSpecified;
        
        private alumno usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comentario comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public evento evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
                this.RaisePropertyChanged("evento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public post post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
                this.RaisePropertyChanged("post");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public reaccionTipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public alumno usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public enum reaccionTipo {
        
        /// <remarks/>
        LIKE,
        
        /// <remarks/>
        DISLIKE,
        
        /// <remarks/>
        LOVE,
        
        /// <remarks/>
        JAJA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/")]
    public partial class interes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEventoPorId", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class buscarEventoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public buscarEventoPorIdRequest() {
        }
        
        public buscarEventoPorIdRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEventoPorIdResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class buscarEventoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.EventoWS.evento @return;
        
        public buscarEventoPorIdResponse() {
        }
        
        public buscarEventoPorIdResponse(PucpConnectPresentacion.EventoWS.evento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class crearEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ubicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int creadorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string interesesIds;
        
        public crearEventoRequest() {
        }
        
        public crearEventoRequest(string nombre, string descripcion, string fecha, string fechaFin, string ubicacion, int creadorId, string interesesIds) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.fecha = fecha;
            this.fechaFin = fechaFin;
            this.ubicacion = ubicacion;
            this.creadorId = creadorId;
            this.interesesIds = interesesIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class crearEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public crearEventoResponse() {
        }
        
        public crearEventoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventos", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarEventosRequest {
        
        public listarEventosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.EventoWS.evento[] @return;
        
        public listarEventosResponse() {
        }
        
        public listarEventosResponse(PucpConnectPresentacion.EventoWS.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unirseAEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class unirseAEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public unirseAEventoRequest() {
        }
        
        public unirseAEventoRequest(int idEvento, int idAlumno) {
            this.idEvento = idEvento;
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unirseAEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class unirseAEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public unirseAEventoResponse() {
        }
        
        public unirseAEventoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorInteres", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarEventosPorInteresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarEventosPorInteresRequest() {
        }
        
        public listarEventosPorInteresRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorInteresResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarEventosPorInteresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.EventoWS.evento[] @return;
        
        public listarEventosPorInteresResponse() {
        }
        
        public listarEventosPorInteresResponse(PucpConnectPresentacion.EventoWS.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInteresesPorEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarInteresesPorEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarInteresesPorEventoRequest() {
        }
        
        public listarInteresesPorEventoRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInteresesPorEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarInteresesPorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.EventoWS.interes[] @return;
        
        public listarInteresesPorEventoResponse() {
        }
        
        public listarInteresesPorEventoResponse(PucpConnectPresentacion.EventoWS.interes[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarParticipacionEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class cancelarParticipacionEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public cancelarParticipacionEventoRequest() {
        }
        
        public cancelarParticipacionEventoRequest(int idEvento, int idUsuario) {
            this.idEvento = idEvento;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarParticipacionEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class cancelarParticipacionEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelarParticipacionEventoResponse() {
        }
        
        public cancelarParticipacionEventoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarParticipacionEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class verificarParticipacionEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public verificarParticipacionEventoRequest() {
        }
        
        public verificarParticipacionEventoRequest(int idEvento, int idUsuario) {
            this.idEvento = idEvento;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarParticipacionEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class verificarParticipacionEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public verificarParticipacionEventoResponse() {
        }
        
        public verificarParticipacionEventoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarParticipacionEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class registrarParticipacionEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public registrarParticipacionEventoRequest() {
        }
        
        public registrarParticipacionEventoRequest(int idEvento, int idAlumno) {
            this.idEvento = idEvento;
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarParticipacionEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class registrarParticipacionEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public registrarParticipacionEventoResponse() {
        }
        
        public registrarParticipacionEventoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantesPorEvento", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarParticipantesPorEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarParticipantesPorEventoRequest() {
        }
        
        public listarParticipantesPorEventoRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantesPorEventoResponse", WrapperNamespace="http://ws.pucpconnect.pe.edu.pucp/", IsWrapped=true)]
    public partial class listarParticipantesPorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pucpconnect.pe.edu.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PucpConnectPresentacion.EventoWS.alumno[] @return;
        
        public listarParticipantesPorEventoResponse() {
        }
        
        public listarParticipantesPorEventoResponse(PucpConnectPresentacion.EventoWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventoWSChannel : PucpConnectPresentacion.EventoWS.EventoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoWSClient : System.ServiceModel.ClientBase<PucpConnectPresentacion.EventoWS.EventoWS>, PucpConnectPresentacion.EventoWS.EventoWS {
        
        public EventoWSClient() {
        }
        
        public EventoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse PucpConnectPresentacion.EventoWS.EventoWS.cancelarParticipacion(PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest request) {
            return base.Channel.cancelarParticipacion(request);
        }
        
        public bool cancelarParticipacion(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest inValue = new PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).cancelarParticipacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse> PucpConnectPresentacion.EventoWS.EventoWS.cancelarParticipacionAsync(PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest request) {
            return base.Channel.cancelarParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionResponse> cancelarParticipacionAsync(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest inValue = new PucpConnectPresentacion.EventoWS.cancelarParticipacionRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).cancelarParticipacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse PucpConnectPresentacion.EventoWS.EventoWS.buscarEventoPorId(PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest request) {
            return base.Channel.buscarEventoPorId(request);
        }
        
        public PucpConnectPresentacion.EventoWS.evento buscarEventoPorId(int idEvento) {
            PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest inValue = new PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest();
            inValue.idEvento = idEvento;
            PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).buscarEventoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse> PucpConnectPresentacion.EventoWS.EventoWS.buscarEventoPorIdAsync(PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest request) {
            return base.Channel.buscarEventoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.buscarEventoPorIdResponse> buscarEventoPorIdAsync(int idEvento) {
            PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest inValue = new PucpConnectPresentacion.EventoWS.buscarEventoPorIdRequest();
            inValue.idEvento = idEvento;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).buscarEventoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.crearEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.crearEvento(PucpConnectPresentacion.EventoWS.crearEventoRequest request) {
            return base.Channel.crearEvento(request);
        }
        
        public bool crearEvento(string nombre, string descripcion, string fecha, string fechaFin, string ubicacion, int creadorId, string interesesIds) {
            PucpConnectPresentacion.EventoWS.crearEventoRequest inValue = new PucpConnectPresentacion.EventoWS.crearEventoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.fecha = fecha;
            inValue.fechaFin = fechaFin;
            inValue.ubicacion = ubicacion;
            inValue.creadorId = creadorId;
            inValue.interesesIds = interesesIds;
            PucpConnectPresentacion.EventoWS.crearEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).crearEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.crearEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.crearEventoAsync(PucpConnectPresentacion.EventoWS.crearEventoRequest request) {
            return base.Channel.crearEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.crearEventoResponse> crearEventoAsync(string nombre, string descripcion, string fecha, string fechaFin, string ubicacion, int creadorId, string interesesIds) {
            PucpConnectPresentacion.EventoWS.crearEventoRequest inValue = new PucpConnectPresentacion.EventoWS.crearEventoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.fecha = fecha;
            inValue.fechaFin = fechaFin;
            inValue.ubicacion = ubicacion;
            inValue.creadorId = creadorId;
            inValue.interesesIds = interesesIds;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).crearEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.listarEventosResponse PucpConnectPresentacion.EventoWS.EventoWS.listarEventos(PucpConnectPresentacion.EventoWS.listarEventosRequest request) {
            return base.Channel.listarEventos(request);
        }
        
        public PucpConnectPresentacion.EventoWS.evento[] listarEventos() {
            PucpConnectPresentacion.EventoWS.listarEventosRequest inValue = new PucpConnectPresentacion.EventoWS.listarEventosRequest();
            PucpConnectPresentacion.EventoWS.listarEventosResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosResponse> PucpConnectPresentacion.EventoWS.EventoWS.listarEventosAsync(PucpConnectPresentacion.EventoWS.listarEventosRequest request) {
            return base.Channel.listarEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosResponse> listarEventosAsync() {
            PucpConnectPresentacion.EventoWS.listarEventosRequest inValue = new PucpConnectPresentacion.EventoWS.listarEventosRequest();
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.unirseAEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.unirseAEvento(PucpConnectPresentacion.EventoWS.unirseAEventoRequest request) {
            return base.Channel.unirseAEvento(request);
        }
        
        public bool unirseAEvento(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.unirseAEventoRequest inValue = new PucpConnectPresentacion.EventoWS.unirseAEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            PucpConnectPresentacion.EventoWS.unirseAEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).unirseAEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.unirseAEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.unirseAEventoAsync(PucpConnectPresentacion.EventoWS.unirseAEventoRequest request) {
            return base.Channel.unirseAEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.unirseAEventoResponse> unirseAEventoAsync(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.unirseAEventoRequest inValue = new PucpConnectPresentacion.EventoWS.unirseAEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).unirseAEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse PucpConnectPresentacion.EventoWS.EventoWS.listarEventosPorInteres(PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest request) {
            return base.Channel.listarEventosPorInteres(request);
        }
        
        public PucpConnectPresentacion.EventoWS.evento[] listarEventosPorInteres(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest inValue = new PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest();
            inValue.idEvento = idEvento;
            PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarEventosPorInteres(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse> PucpConnectPresentacion.EventoWS.EventoWS.listarEventosPorInteresAsync(PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest request) {
            return base.Channel.listarEventosPorInteresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarEventosPorInteresResponse> listarEventosPorInteresAsync(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest inValue = new PucpConnectPresentacion.EventoWS.listarEventosPorInteresRequest();
            inValue.idEvento = idEvento;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarEventosPorInteresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.listarInteresesPorEvento(PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest request) {
            return base.Channel.listarInteresesPorEvento(request);
        }
        
        public PucpConnectPresentacion.EventoWS.interes[] listarInteresesPorEvento(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest inValue = new PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest();
            inValue.idEvento = idEvento;
            PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarInteresesPorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.listarInteresesPorEventoAsync(PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest request) {
            return base.Channel.listarInteresesPorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarInteresesPorEventoResponse> listarInteresesPorEventoAsync(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest inValue = new PucpConnectPresentacion.EventoWS.listarInteresesPorEventoRequest();
            inValue.idEvento = idEvento;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarInteresesPorEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.cancelarParticipacionEvento(PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest request) {
            return base.Channel.cancelarParticipacionEvento(request);
        }
        
        public bool cancelarParticipacionEvento(int idEvento, int idUsuario) {
            PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idUsuario = idUsuario;
            PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).cancelarParticipacionEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.cancelarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest request) {
            return base.Channel.cancelarParticipacionEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoResponse> cancelarParticipacionEventoAsync(int idEvento, int idUsuario) {
            PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.cancelarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idUsuario = idUsuario;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).cancelarParticipacionEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.verificarParticipacionEvento(PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest request) {
            return base.Channel.verificarParticipacionEvento(request);
        }
        
        public bool verificarParticipacionEvento(int idEvento, int idUsuario) {
            PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idUsuario = idUsuario;
            PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).verificarParticipacionEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.verificarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest request) {
            return base.Channel.verificarParticipacionEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.verificarParticipacionEventoResponse> verificarParticipacionEventoAsync(int idEvento, int idUsuario) {
            PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.verificarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idUsuario = idUsuario;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).verificarParticipacionEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.registrarParticipacionEvento(PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest request) {
            return base.Channel.registrarParticipacionEvento(request);
        }
        
        public bool registrarParticipacionEvento(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).registrarParticipacionEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.registrarParticipacionEventoAsync(PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest request) {
            return base.Channel.registrarParticipacionEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.registrarParticipacionEventoResponse> registrarParticipacionEventoAsync(int idEvento, int idAlumno) {
            PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest inValue = new PucpConnectPresentacion.EventoWS.registrarParticipacionEventoRequest();
            inValue.idEvento = idEvento;
            inValue.idAlumno = idAlumno;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).registrarParticipacionEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse PucpConnectPresentacion.EventoWS.EventoWS.listarParticipantesPorEvento(PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest request) {
            return base.Channel.listarParticipantesPorEvento(request);
        }
        
        public PucpConnectPresentacion.EventoWS.alumno[] listarParticipantesPorEvento(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest inValue = new PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest();
            inValue.idEvento = idEvento;
            PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse retVal = ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarParticipantesPorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse> PucpConnectPresentacion.EventoWS.EventoWS.listarParticipantesPorEventoAsync(PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest request) {
            return base.Channel.listarParticipantesPorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoResponse> listarParticipantesPorEventoAsync(int idEvento) {
            PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest inValue = new PucpConnectPresentacion.EventoWS.listarParticipantesPorEventoRequest();
            inValue.idEvento = idEvento;
            return ((PucpConnectPresentacion.EventoWS.EventoWS)(this)).listarParticipantesPorEventoAsync(inValue);
        }
    }
}
